sudo: required
services:
   - docker

before_install:
  - docker build -t deb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "my-docker-app"
  env: "My-docker-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-817087517801"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"